# โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ
# ะะปะฐะณะธะฝ ะฟัะธะฝะฐะดะปะตะถะธั UnixMC: vk.com/unix_mc
# ะัะธ ะฒะพะทะฝะธะบะฝะพะฒะตะฝะธะธ ะฒะพะฟัะพัะพะฒ ะธะปะธ ะฟัะพะฑะปะตะผ ะฒ ัะฐะฑะพัะต ะฟะปะฐะณะธะฝะฐ
# ะธัะฟะพะปัะทัะนัะต "!ัะฒัะทั ั ะฟะพะดะดะตัะถะบะพะน" ะฒ ะฑะพัะต ะณััะฟะฟั
# ะะตะบะพะผะตะฝะดัะตะผะฐั ะฒะตััะธั ัะดัะฐ: 1.12.2
# report_mode: #1-ะะตัะตะดะฐ 2-ะะธะฐะปะพะณ
# user_id - ะธัะฟะพะปัะทัะตััั ะฟัะธ report_mode=2
# unixreport.use - ะฟัะฐะฒะพ ะฝะฐ ะพัะฟัะฐะฒะบั ะถะฐะปะพะฑั
# unixreport.immunity - ะฟัะฐะฒะพ ะฝะฐ ะธะผะผัะฝะธัะตั ะพั ะถะฐะปะพะฑั
# โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ โ

access_token: "ะฒะฐั ัะพะบะตะฝ ะทะดะตัั"
peer_id: "ID ะฑะตัะตะดั ะทะดะตัั"
server_name: "ะฝะฐะทะฒะฐะฝะธะต ัะตัะฒะตัะฐ"
report_mode: 1
report_delay_sec: 120
user_id: ะฒะฐั_ID_ัััะฐะฝะธัั_ะทะดะตัั
reason_min_symbols: 3

messages:
  prefix: "ยงe|"
  report_send: "ยงfะั ะพัะฟัะฐะฒะธะปะธ ะถะฐะปะพะฑั ะฝะฐ ะธะณัะพะบะฐ ยงe%player%"
  report_chat: "@online #ticket\nโ ะะพัััะฟะธะปะฐ ะถะฐะปะพะฑะฐ โ\n\n๐ค ะะณัะพะบ: %player_1%\nโ ะะฐัััะธัะตะปั: %player_2%\n๐ฌ ะัะธัะธะฝะฐ: %reason%\n\n๐ ะกะตัะฒะตั: %server_name%"
  not_enough_perm: "ยงfะฃ ะฒะฐั ะฝะตะดะพััะฐัะพัะฝะพ ะฟัะฐะฒ"
  error: "ยงfะัะฟัะฐะฒะธัั ะถะฐะปะพะฑั: ยงe/report <ะฝะธะบ_ะธะณัะพะบะฐ> <ะฟัะธัะธะฝะฐ>"
  error_min_symbols: "ยงfะะธะฝะธะผะฐะปัะฝะพะต ะบะพะปะธัะตััะฒะพ ัะธะผะฒะพะปะพะฒ ะฒ ะฟัะธัะธะฝะต: ยงe%min%"
  error_delay: "ยงfะะพะดะพะถะดะธัะต ยงe%sec% ัะตะบัะฝะด ยงfะฟะตัะตะด ะธัะฟะพะปัะทะพะฒะฐะฝะธะตะผ ััะพะน ะบะพะผะฐะฝะดั"
  not_online: "ยงfะะณัะพะบ ยงe%player% ยงfะฝะต ะฒ ัะตัะธ"
  player_you: "ยงfะั ะฝะต ะผะพะถะตัะต ะพัะฟัะฐะฒะธัั ัะตะฟะพัั ะฝะฐ ัะฐะผะพะณะพ ัะตะฑั"
  player_immunity: "ยงfะั ะฝะต ะผะพะถะตัะต ะพัะฟัะฐะฒะธัั ัะตะฟะพัั ะฝะฐ ััะพะณะพ ัะตะปะพะฒะตะบะฐ"